quartz:
  enabled: false
spring:
  resources:
    static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://172.16.0.165:3306/shiro?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-total: 150
      min-idle: 10
      max-idle: 30
      initial-size: 806
      log-abandoned: true
      remove-abandoned-on-borrow: false
      remove-abandoned-timeout: 10
      max-wait-millis: 10000
      time-between-eviction-runs-millis: 10000
      num-tests-per-eviction-run: 10
      min-evictable-idle-time-millis: 10000
      validation-query: "select 'a' from dual"
      test-on-borrow: false
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    encoding: utf-8
    excluded-view-names:
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    template-resolver-order: 1
  redis:
    host: localhost
    jedis:
      pool:
        max-active: 30
        max-wait: 1000ms
        max-idle: 8
    port: 6379
#    上传文件大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 52428800
      max-request-size: 52428800
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8888
#  servlet:
#    context-path: /aaa
logging:
  config: classpath:logback.xml
  level:
    root: info
shiro-customer:
  session-time-out: -1000 #session永不过期
  chains:
    member-testDrawImg: anon
common-config:
  upload-path: static/images/
